import { surprises, type Effects, type GameContent, type Condition } from '@game/game-content';
import { clamp, SAVE_SCHEMA_VERSION } from '@game/shared';
import { nextRandom } from './rng.js';
import type { Command, GameState } from './types.js';

export const initialState = (seed: number): GameState => ({ schemaVersion: SAVE_SCHEMA_VERSION, seed, rngState: seed | 0, rngVersion: 'mulberry32-v1', month: 1, actionPoints: 2, stats: { knowledge: 40, skill: 30, health: 70, spirit: 60, money: 45, debt: 0, morality: 55 }, relationships: { lan: 15, huy: 15, phong: 15, family: 15 }, traits: { disciplined: 0, workaholic: 0, empathetic: 0, avoidant: 0, gambler: 0, reliable: 0, familyOriented: 0 }, flags: { graduated: false }, history: [], eventRuntime: {}, delayed: [] });
const get = (s: GameState, path: string): unknown => path.split('.').reduce<unknown>((v, k) => typeof v === 'object' && v !== null ? (v as Record<string, unknown>)[k] : undefined, s);
export const meets = (s: GameState, c: Condition) => { const v = get(s, c.field); return c.op === 'eq' ? v === c.value : c.op === 'gte' ? Number(v) >= Number(c.value) : Number(v) <= Number(c.value); };
export function applyEffects(s: GameState, e: Effects): GameState { const n = structuredClone(s); for (const [k, v] of Object.entries(e.stats ?? {})) n.stats[k as keyof typeof n.stats] = k === 'money' || k === 'debt' ? Math.max(0, n.stats[k as keyof typeof n.stats] + v) : clamp(n.stats[k as keyof typeof n.stats] + v); for (const [k, v] of Object.entries(e.relationships ?? {})) n.relationships[k] = clamp((n.relationships[k] ?? 0) + v); for (const [k, v] of Object.entries(e.traits ?? {})) n.traits[k] = clamp((n.traits[k] ?? 0) + v); Object.assign(n.flags, e.flags); return n; }
export function scheduleEvent(s: GameState, c: GameContent): GameState { const eligible = c.events.filter(e => (e.month === undefined || e.month <= s.month) && e.prerequisite.every(x => meets(s, x)) && (!e.oneShot || !s.eventRuntime[e.id]) && s.month - (s.eventRuntime[e.id]?.lastMonth ?? -999) > e.cooldown); if (!eligible.length) return s; const forced = eligible.find(e => e.mandatory && (e.deadline ?? 99) <= s.month); const total = eligible.reduce((a, e) => a + e.weight * (e.deadline ? 1 + Math.max(0, s.month - e.deadline + 2) * 3 : 1), 0); const r = nextRandom(s.rngState); let pick = forced; let cursor = r.value * total; for (const e of eligible) { cursor -= e.weight * (e.deadline ? 1 + Math.max(0, s.month - e.deadline + 2) * 3 : 1); if (cursor <= 0) { pick ??= e; break; } } return { ...s, rngState: r.state, pendingEvent: pick?.id }; }
function scheduleSurprise(s: GameState, activityId: string): GameState { const year = Math.min(4, Math.ceil(s.month / 12)); const eligible = surprises.filter(x => x.years.includes(year) && x.afterActivities.includes(activityId) && x.prerequisite.every(c => meets(s, c)) && !(s.seenSurprises ?? []).includes(x.id)); if (!eligible.length) return s; const roll = nextRandom(s.rngState); const n = { ...s, rngState: roll.state }; if (roll.value > 0.24) return n; const pickRoll = nextRandom(n.rngState); const total = eligible.reduce((sum, x) => sum + x.weight, 0); let cursor = pickRoll.value * total; let pick = eligible[0]!; for (const item of eligible) { cursor -= item.weight; if (cursor <= 0) { pick = item; break; } } return { ...n, rngState: pickRoll.state, pendingSurprise: pick.id }; }
export function resolveEnding(s: GameState, c: GameContent): string | undefined { return [...c.endings].sort((a, b) => b.priority - a.priority).find(e => e.conditions.every(x => meets(s, x)))?.id; }
const chose = (s: GameState, kind: 'event' | 'surprise', id: string, choices?: string[]) => s.history.some(entry => { const match = new RegExp(`^m\\d+:${kind}:${id}:([^:]+)$`).exec(entry); return !!match && (!choices || choices.includes(match[1]!)); });
function deriveEndingFlags(s: GameState): GameState { const canonical = ['lan', 'huy', 'phong', 'family'].map(key => s.relationships[key] ?? 0); const graduated = chose(s, 'event', 'graduation-exam', ['study-plan', 'cram']) && s.stats.knowledge >= 35; const internship = chose(s, 'event', 'internship', ['accept', 'part-time']); const freelancer = !!s.flags.planFreelance && s.stats.skill >= 55 && (internship || s.history.some(x => x.includes(':activity:skill_training'))); const returnHome = !!s.flags.planReturnHome && (s.relationships.family ?? 0) >= 45; const friend = [s.relationships.lan ?? 0, s.relationships.huy ?? 0, s.relationships.phong ?? 0].some(value => value >= 30); const careerReady = s.stats.knowledge >= 55 && s.stats.skill >= 50; return { ...s, flags: { ...s.flags, graduated, cannotGraduate: !graduated, freelancer, returnHome, allRelationshipsLow: canonical.every(value => value <= 10), balancedSuccess: graduated && s.stats.knowledge >= 60 && s.stats.skill >= 55 && s.stats.health >= 45 && s.stats.spirit >= 45 && (s.relationships.family ?? 0) >= 30 && friend, successUnwell: graduated && careerReady && (s.stats.health <= 25 || s.stats.spirit <= 20) } }; }
const finish = (s: GameState, c: GameContent): GameState => { const n = deriveEndingFlags(s); return { ...n, ending: resolveEnding(n, c) }; };
const queueDelayed = (n: GameState, items: Array<{ afterMonths: number; effects: Effects; source?: string; prose?: string }>, source: string) => n.delayed.push(...items.map(d => ({ dueMonth: n.month + d.afterMonths, effects: d.effects, source: d.source ?? source, prose: d.prose })));
export function dispatch(state: GameState, cmd: Command, c: GameContent): GameState {
	if (cmd.type === 'START_GAME') return initialState(cmd.seed);
	if (cmd.type === 'RESTORE_SAVE') return structuredClone(cmd.state);
	if (cmd.type === 'CONFIRM_STOP_JOURNEY') return { ...state, flags: { ...state.flags, stopped: true }, ending: 'stop_midway' };
	if (cmd.type === 'SELECT_ACTIVITY') { if (state.actionPoints <= 0 || state.pendingEvent || state.pendingSurprise) throw new Error('Không thể chọn activity'); const a = c.activities.find(x => x.id === cmd.activityId); if (!a) throw new Error('Activity không tồn tại'); let n = applyEffects(state, a.effects); n.actionPoints--; n.history.push(`m${n.month}:activity:${a.id}`); queueDelayed(n, a.delayed, `activity:${a.id}`); return scheduleSurprise(n, a.id); }
	if (cmd.type === 'CHOOSE_SURPRISE_OPTION') { if (state.pendingSurprise !== cmd.surpriseId) throw new Error('Tình huống không active'); const surprise = surprises.find(x => x.id === cmd.surpriseId); const choice = surprise?.choices.find(x => x.id === cmd.choiceId); if (!surprise || !choice) throw new Error('Lựa chọn tình huống không tồn tại'); let n = applyEffects(state, choice.effects); n.pendingSurprise = undefined; n.seenSurprises = [...(n.seenSurprises ?? []), surprise.id]; n.history.push(`m${n.month}:surprise:${surprise.id}:${choice.id}`); queueDelayed(n, choice.delayed, `surprise:${surprise.id}:${choice.id}`); return n.month >= 48 ? finish(n, c) : n; }
	if (cmd.type === 'CHOOSE_EVENT_OPTION') { if (state.pendingEvent !== cmd.eventId) throw new Error('Event không active'); const e = c.events.find(x => x.id === cmd.eventId); const choice = e?.choices.find(x => x.id === cmd.choiceId); if (!e || !choice) throw new Error('Choice không tồn tại'); let n = applyEffects(state, choice.effects); n.pendingEvent = undefined; n.eventRuntime[e.id] = { lastMonth: n.month, times: (n.eventRuntime[e.id]?.times ?? 0) + 1 }; n.history.push(`m${n.month}:event:${e.id}:${choice.id}`); queueDelayed(n, choice.delayed, `event:${e.id}:${choice.id}`); return n.month >= 48 ? finish(n, c) : n; }
	if (state.actionPoints > 0 || state.pendingSurprise) throw new Error('Còn lựa chọn chưa giải quyết');
	const finalSeason = state.month >= 46; let n = { ...state, month: finalSeason ? 48 : state.month + 3, actionPoints: finalSeason ? 0 : 2 };
	for (const d of n.delayed.filter(x => x.dueMonth <= n.month)) { n = applyEffects(n, d.effects); n.history.push(`m${n.month}:delayed:${encodeURIComponent(d.source ?? 'legacy')}:${encodeURIComponent(d.prose ?? 'Hệ quả từ lựa chọn trước đã tới.')}`); }
	n.delayed = n.delayed.filter(x => x.dueMonth > n.month); n = scheduleEvent(n, c); if (n.month === 48 && !n.pendingEvent) n = finish(n, c); return n;
}
